### ISSUE TITLE
Spelling mistake, Incorrect Abbreviation, Grammar Mistake 

### ISSUE THREAD

**Issue by fathimasulthanaas** [VARSHAV2001/cms#2]
There is a spelling mistake in the word cancellation   **LINE**  18****
Correct abbreviation of SRS is Software Requirement Specifications.  **Line** **31**
Spelling mistakes for CHARTACTERS, SYMBOLS, SPECIAL   ****Line**55**
The word "if" is written in block letters  ****Line**57*
Written as "their" for "there" ****Line**57**
Grammar mistake....It must be minimum    **Line** ****59**60**
****Line**61**  same mistake as ****Line**55**
Spelling mistake for word  "Confirmation" ****Line**62**
Used blocked letters for word "If"       ****Line**82**

**Comment by VARSHAV2001** [comment]
Mistake are corrected and update the CMS
